---
- name: Configure Kubernetes Cluster
  hosts: all
  become: yes
  tasks:
    - name: Remove malformed Kubernetes apt repository file (if exists)
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/pkgs_k8s_io_core_stable_v1_31_deb.list
        state: absent

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install dependencies for Kubernetes
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Add Docker repository GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Install Docker CE
      apt:
        name: docker-ce
        state: present

    - name: Ensure Docker service is enabled and started
      service:
        name: docker
        enabled: yes
        state: started

    - name: Download kubectl binary
      shell: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        mv kubectl /usr/local/bin/kubectl

    - name: Verify kubectl installation
      command: kubectl version --client
      register: kubectl_version

    - name: Display kubectl version
      debug:
        msg: "{{ kubectl_version.stdout }}"

- name: Initialize Kubernetes Master (Control Plane)
  hosts: master
  become: yes
  tasks:
    - name: Initialize Kubernetes Cluster
      command: kubeadm init --pod-network-cidr=10.244.0.0/16
      register: kubeadm_output
      ignore_errors: yes

    - name: Save kubeadm join command to file
      copy:
        content: "{{ kubeadm_output.stdout }}"
        dest: /tmp/kubeadm_init_output.txt

    - name: Create .kube directory for root user
      file:
        path: /root/.kube
        state: directory
        mode: 0755

    - name: Copy admin.conf to .kube/config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /root/.kube/config
        remote_src: yes
        owner: root
        group: root
        mode: 0644

    - name: Set correct ownership for .kube/config
      file:
        path: /root/.kube/config
        owner: root
        group: root
        mode: '0600'

- name: Join Kubernetes Worker Nodes to Cluster
  hosts: worker
  become: yes
  tasks:
    - name: Gather kubeadm join command from master
      slurp:
        src: /tmp/kubeadm_init_output.txt
      delegate_to: master
      register: join_command

    - name: Execute kubeadm join command
  command: |
    kubeadm join 91.91.91.32:6443 --token e8j2by.rxemxgh842lfdjil \
      --discovery-token-ca-cert-hash sha256:9f43e0d5dab6f51a63a9d9c34ce6fd6b5e2077c5cbb5ad7910f3a0eff8ae2b9b
  args:
    executable: /bin/bash


