---
- name: Install Docker and Docker Compose
  hosts: all
  become: yes

  tasks:
    - name: Update the apt package index
      apt:
        update_cache: yes

    - name: Install prerequisites
      apt:
        name:
          - ca-certificates
          - curl
        state: present

    - name: Create Docker keyring directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker’s official GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Add Docker repository
      apt_repository:
        repo: 'deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable'
        filename: docker
        update_cache: yes

    - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Download the latest version of Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.29.6/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Copy Docker Compose to /usr/bin for easier access
      copy:
        src: /usr/local/bin/docker-compose
        dest: /usr/bin/docker-compose
        remote_src: yes
        mode: '0755'

    - name: Verify Docker Compose installation
      command: docker-compose --version
      register: compose_version

    - name: Show Docker Compose version
      debug:
        msg: "{{ compose_version.stdout }}"

